spring:
  datasource:
    username: wreczyck
    password: ${MORFEUSZ_PASSWORD}
    url: jdbc:sqlserver://morfeusz.wszib.edu.pl:1433;databaseName=wreczyck;encrypt=false;
  liquibase:
    change-log: classpath:db/changelog/changelog-master.json
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
